### ISSUE TITLE
Issue setting enable_extension in config.yml Symfony2 on server

### ISSUE THREAD

**Issue by rebase-master** [ThePhalcons/AmazonWebServicesBundle#19]
Installed Cybernox bundle and set up configuration in parameters.yml and config.yml.
In config.yml the settings are as follows:
# Amazon Web Services Configuration

cybernox_amazon_web_services:
    key:                        %aws_key%
    secret:                     %aws_secret%
    default_cache_config:       apc
    enable_extensions:          true
    certificate_authority:      false
    disable_auto_config:        false

The bundle is configured correctly and is working in development environment but the same is not working on server.

I get this error when I try to clear the cache: The parameter "cybernox_amazon_web_services.enable_extensions" must be defined.

Is there a override for this extension somewhere?

**Comment by MrNicodemuz** [comment]
I ran into the same issue. Clearing cache first for dev, and then prod solved the issue.

I think this is still a valid issue and should be fixed? @mbadolato

**Comment by mbadolato** [comment]
@MrNicodemuz I no longer maintain this bundle but perhaps @Mehdi-CodeIsLife could look into it if/when he has the time. However, being that this is a cache clearing issue, I don't know that there's really much that can be done. There are a few bundles I've worked with in Symfony projects that have the same issue
