### ISSUE TITLE
Amazon Route 53?

### ISSUE THREAD

**Issue by jjbier** [ThePhalcons/AmazonWebServicesBundle#33]
Can you add support for Amazon Route 53?

**Comment by Mehdi-CodeIsLife** [comment]
Amazon Route 53 is now supported you can use it as following 

public function someAction()
{
    // Get a AmazonRoute53 object
    $route = $this->container->get('aws_Route53');

    // Get a message from an existing queue
    $response = $route->listHostedZones(array(
                                'Marker' => 'string',
                                'MaxItems' => 'string',
                                'DelegationSetId' => 'string',
                       ));

    // Do stuff 
    // ...
}
